core_crm/urls.py
from django.contrib import admin
from django.urls import include, path
from dashboards.views import index, about

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("__reload__/", include("django_browser_reload.urls")),  # django_tailwind
    path("", index, name="homepage"),
    path("about/", about, name="about"),
    path("account/", include("accounts.urls")),
    path("client/", include("clients.urls")),
    path("dashboard/", include("dashboards.urls")),
    path("team/", include("teams.urls")),
    path("lead/", include("leads.urls")),
]

leads/urls.py
from django.urls import path
from . import views

app_name = "leads"
urlpatterns = [
    path("", views.LeadListView.as_view(), name="lead_list"),
    path("add/", views.LeadCreateView.as_view(), name="lead_create"),
    path("<int:pk>/", views.LeadDetailView.as_view(), name="lead_detail"),
    path("<int:pk>/update/", views.LeadUpdateView.as_view(), name="lead_update"),
    path("<int:pk>/delete/", views.LeadDeleteView.as_view(), name="lead_delete"),
    path("<int:pk>/convert/", views.LeadConvertToClientView.as_view(), name="lead_convert"),
]

leads/models.py
from django.contrib.auth.models import User
from django.db import models

from teams.models import Team


class Lead(models.Model):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"

    CHOICES_PRIORITY = (
        (LOW, "Low"),
        (MEDIUM, "Medium"),
        (HIGH, "High"),
    )

    NEW = "new"
    CONTACTED = "contacted"
    WON = "won"
    LOST = "lost"

    CHOICES_STATUS = (
        (NEW, "New"),
        (CONTACTED, "Contacted"),
        (WON, "Won"),
        (LOST, "Lost"),
    )

    team = models.ForeignKey(Team, related_name="leads", on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    description = models.TextField(null=True, blank=True)
    priority = models.CharField(max_length=6, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=9, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name="leads", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("created_at",)

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"
    
    def get_absolute_url(self):
        return reverse("leads:lead_detail", kwargs={"pk": self.pk})

leads/forms.py
from django import forms

from .models import Lead, Comment


class LeadCreateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            "team",
            "first_name",
            "last_name",
            "email",
            "description",
            "priority",
            "status",
        )
        widgets = {
            "description": forms.Textarea(attrs={"rows": 4, "cols": 15}),
        }


class LeadAddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)
        widgets = {
            "content": forms.Textarea(attrs={"rows": 4, "cols": 10}),
        }

leads/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from .forms import LeadCreateForm
from .models import Lead

from clients.models import Client
from teams.models import Team


@login_required
def lead_list_view(request):
    leads = Lead.objects.filter(created_by=request.user, converted_to_client=False)
    context = {
        "leads": leads,
    }
    return render(request, "leads/lead_list.html", context)


@login_required
def lead_create_view(request):

    team = Team.objects.filter(created_by=request.user)
    lead_count = team.leads.count()
    max_leads = team.plan.max_leads

    if request.method == "POST":
        form = LeadCreateForm(request.POST)
        if form.is_valid():
            lead = form.save(commit=False)
            lead.created_by = request.user
            lead.team = team
            lead.save()
            messages.success(request, "Lead created sucessfully!")
            return redirect("leads:lead_list")
    else:
        form = LeadCreateForm()

    context = {
        "form": form,
        "team": team,
        "lead_count": lead_count,
        "max_leads": max_leads,
    }
    return render(request, "leads/lead_create.html", context)


@login_required
def lead_detail_view(request, pk):
    
    try:
        lead = get_object_or_404(Lead, created_by=request.user, id=pk)
    except:
        return HttpResponse("Not ALLOWED!")

    context = {
        "lead": lead,
    }
    return render(request, "leads/lead_detail.html", context)


@login_required
def lead_update_view(request, pk):

    try:
        lead = get_object_or_404(Lead, created_by=request.user, id=pk)
    except:
        return HttpResponse("Not ALLOWED!")

    if request.method == "POST":
        form = LeadCreateForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            messages.success(request, "Lead updated sucessfully!")
            return redirect("leads:lead_detail", lead.pk)
    else:
        form = LeadCreateForm(instance=lead)

    context = {
        "lead": lead,
        "form": form,
    }
    return render(request, "leads/lead_update.html", context)


@login_required
def lead_delete_view(request, pk):
    
    try:
        lead = get_object_or_404(Lead, created_by=request.user, id=pk)
    except:
        return HttpResponse("Not ALLOWED!")

    if request.method == "POST":
        lead.delete()
        messages.success(request, "Lead deleted sucessfully!")
        return redirect("leads:lead_list")

    context = {
        "lead": lead,
    }
    return render(request, "leads/lead_delete.html", context)


@login_required
def convert_to_client_view(request, pk):

    lead = get_object_or_404(Lead, created_by=request.user, id=pk)
    team = Team.objects.filter(created_by=request.user).first()

    Client.objects.create(
        team=team,
        first_name=lead.first_name,
        last_name=lead.last_name,
        email=lead.email,
        description=lead.description,
        created_by=request.user,
    )
    lead.converted_to_client = True
    lead.save()
    messages.success(request, "Lead converted to client sucessfully!")
    return redirect("leads:lead_list")

leads/templates/leads/lead_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block title %}Add Lead{% endblock title %}


{% block main_content %}
<div class="container px-5 py-16 mx-auto">
    <div class="lg:w-2/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h1 class="text-4xl text-gray-800">Create a new lead</h1>
            {% if lead_count < max_leads %}
            <form method="post" class="mt-5">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                    Create
                </button>
            </form>
            {% else %}
            <p class='mt-2 mb-2'>Max Leads: {{ max_leads }}</p>
            <div class="p-4 w-full bg-red-300 border-red-400">
                <p class="text-sm text-red-700">Your team has reached the max lead limit.</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock main_content %}

leads/templates/leads/lead_delete.html
{% extends 'base.html' %}

{% block title %}Lead Delete{% endblock title %}


{% block main_content %}
<div class="max-w-lg mt-20 mx-auto">
    <div class="py-5 border-gray-200">
        <form class="mt-5" action="" method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ lead }}"?</p>
            <button class="w-full mt-5 text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md" type="submit">
                Delete
            </button>
        </form>
        <div class="py-5">
            <a class="hover:text-blue-500 underline" href="{{ lead.get_absolute_url }}">Cancel</a>
        </div>
    </div>
</div>
{% endblock main_content %}

leads/templates/leads/lead_detail.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block title %}Lead Detail{% endblock title %}


{% block main_content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-3/5 mx-auto flex flex-wrap">
            {% include 'messages.html' %}
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead }}</h1>
                <div class="flex mb-4">
                    <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Overview
                    </a>
                    <a href="{% url 'leads:lead_update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Update Details
                    </a>
                </div>
                {% if lead.description %}
                    <p class="leading-relaxed mb-4">{{ lead.description }}</p>
                {% endif %}
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Priority</span>
                    <span class="ml-auto text-gray-900">{{ lead.priority }}</span>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Status</span>
                    <span class="ml-auto text-gray-900">{{ lead.status }}</span>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Created at</span>
                    <span class="ml-auto text-gray-900">{{ lead.created_at }}</span>
                </div>
                <div class="flex border-t border-b mb-6 border-gray-300 py-2">
                    <span class="text-gray-500">Updated at</span>
                    <span class="ml-auto text-gray-900">{{ lead.updated_at }}</span>
                </div>
                <div class="flex">
                    <a href="{% url 'leads:lead_convert' lead.pk %}" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                        Convert to client
                    </a>
                </div>

                <div class="flex-grow border-t-2 border-b-2 mt-2 border-gray-300 py-2 text-lg px-1">
                    <h2 class='text-black mb-2'>Add a Comment</h2>
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                            Comment
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock main_content %}

leads/templates/leads/lead_list.html
{% extends 'base.html' %}

{% block title %}Leads{% endblock title %}


{% block main_content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        {% include 'messages.html' %}
        <div class="w-full mb-6 py-6 flex justify-between item-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Leads</h1>
            </div>
            <div>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:lead_create' %}">Create a new lead</a>
            </div>
        </div>

        <div class="flex flex-col w-full">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                        <table class="min-w-full divide-y divide-gray-200">
                            {% if leads %}
                            <thead class="bg-gray-50">
                                <tr>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        First Name
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Last Name
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Email
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Priority
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Status
                                    </th>
                                    <th scope="col" class="relative px-6 py-3">
                                        <span class="sr-only">Edit</span>
                                    </th>
                                </tr>
                            </thead>
                            {% endif %}
                            <tbody>
                                {% for lead in leads %}
                                <tr class="bg-white">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        <a class="hover:text-indigo-500" href="{{ lead.get_absolute_url }}">{{ lead.first_name }}</a>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {{ lead.last_name }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {{ lead.email }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {% if lead.priority %}
                                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                                {{ lead.priority }}
                                            </span>
                                        {% else %}
                                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">
                                                Unassigned
                                            </span>
                                        {% endif %}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        {% if lead.status %}
                                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                                {{ lead.status }}
                                            </span>
                                        {% else %}
                                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">
                                                Unassigned
                                            </span>
                                        {% endif %}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a href="{% url 'leads:lead_update' lead.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                            Edit
                                        </a>
                                    </td>
                                </tr>

                                {% empty %}

                                <p>There are currently no leads</p>

                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>

{% endblock main_content %}

leads/templates/leads/lead_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block title %}Edit Lead{% endblock title %}


{% block main_content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-3/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead }}</h1>
                <div class="flex mb-4">
                    <a href="{{ lead.get_absolute_url }}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Overview
                    </a>
                    <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Update Details
                    </a>
                </div>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                        Update
                    </button>
                </form>
                <div class="mt-5 py-5 border-t border-gray-200">
                    <a href="{% url 'leads:lead_delete' lead.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                        Delete
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock main_content %}