accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path("detail/", views.my_account_details_view, name="account_detail"),
    path("login/", views.AccountLoginView.as_view(), name="login"),
    path("logout/", views.AccountLogoutView.as_view(), name="logout"),
]

core_crm/urls.py
from django.contrib import admin
from django.urls import include, path
from dashboards.views import index, about

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("__reload__/", include("django_browser_reload.urls")),  # django_tailwind
    path("", index, name="homepage"),
    path("about/", about, name="about"),
    path("account/", include("accounts.urls")),
    path("client/", include("clients.urls")),
    path("dashboard/", include("dashboards.urls")),
    path("team/", include("teams.urls")),
    path("lead/", include("leads.urls")),
]

leads/urls.py
from django.urls import path
from . import views

app_name = "leads"
urlpatterns = [
    path("", views.LeadListView.as_view(), name="lead_list"),
    path("add/", views.LeadCreateView.as_view(), name="lead_create"),
    path("<int:pk>/", views.LeadDetailView.as_view(), name="lead_detail"),
    path("<int:pk>/update/", views.LeadUpdateView.as_view(), name="lead_update"),
    path("<int:pk>/delete/", views.LeadDeleteView.as_view(), name="lead_delete"),
    path("<int:pk>/convert/", views.LeadConvertToClientView.as_view(), name="lead_convert"),
]

teams/urls.py
from django.urls import path
from . import views


app_name = "teams"
urlpatterns = [
    path("<int:pk>/edit/", views.edit_team_view, name="team_edit"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(
        User, related_name="userprofile", on_delete=models.CASCADE
    )

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

from .models import UserProfile

from teams.models import Team


def signup_view(request):

    if request.user.is_authenticated:
        return redirect(settings.LOGIN_REDIRECT_URL)

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            UserProfile.objects.create(user=user)
            messages.success(request, "Account created successfully!")
            return redirect("accounts:login")
    else:
        form = UserCreationForm()

    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


@login_required
def my_account_details_view(request):
    team = Team.objects.filter(created_by=request.user).first()
    context = {
        "team": team,
    }
    return render(request, "accounts/my_account_detail.html", context)


class AccountLoginView(views.LoginView):
    template_name = "accounts/login.html"

    def dispatch(self, request, *args, **kwargs):
        """Block authenticated user from accessing login URL."""
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)
        return super().dispatch(request, *args, **kwargs)


class AccountLogoutView(views.LogoutView):
    template_name = "accounts/logout.html"

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block title %}Login{% endblock title %}


{% block main_content %}
<div class="container px-5 py-10 mx-auto">
    <div class="lg:w-2/5 mx-auto flex flex-wrap">
        {% include 'messages.html' %}
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">

            <div class="py-5 border-b border-gray-200">
                <a class="hover:text-blue-500" href="{% url 'accounts:signup' %}">Don't have an account?</a>
            </div>
            
            <form class="mt-5" action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" type="submit">
                    Login
                </button>
            </form>
            
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="#" class="hover:text-blue-500" href="">
                    Forgot Password?
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock main_content %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block title %}Logout{% endblock title %}

{% block main_content %}
<div class="max-w-lg mt-16 mx-10">
    <h1 class="text-gray-900 text-lg title-font font-medium mb-3">Logged out</h1>
    <p>Thanks for spending some quality time with the Website today.</p>
    <div class="mt-5 py-5 border-t border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'accounts:login' %}">
            Log In
        </a>
    </div>
</div>
{% endblock main_content %}

accounts/templates/accounts/my_account_detail.html
{% extends 'base.html' %}
{% block title %}Account{% endblock title %}

{% block main_content %}

<section class="text-gray-600 body-font">
  <div class="container flex flex-wrap px-20 py-14 mx-auto items-center">
    {% include 'messages.html' %}
    <div class="md:w-1/2 md:pr-12 md:py-8 md:border-b-0 mb-10 md:mb-0 pb-10 border-b border-gray-200">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">MY ACCOUNT</h1>
      <p class="leading-relaxed text-base"><span class='text-black'>Username: </span>{{ request.user.username }}</p>
      <p class="leading-relaxed text-base"><span class='text-black'>Team: </span>{{ team.name }}</p>
      {% if team.created_by == request.user %}
      <a href="{% url 'teams:team_edit' team.pk %}" class="text-indigo-500 inline-flex items-center mt-4">
        Edit
      </a>
      {% endif %}
    </div>
  </div>
</section>
{% endblock main_content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block title %}Sign up{% endblock title %}


{% block main_content %}
<div class="max-w-lg mt-8 mb-8 mx-auto">
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Sign Up
        </button>
    </form>
    <div class="py-5 border-t border-gray-200 mt-5">
        <a class="hover:text-blue-500" href="{% url 'accounts:login' %}">Already have an account?</a>
    </div>
</div>
{% endblock main_content %}