clients/urls.py
from django.urls import path
from . import views

app_name = "clients"
urlpatterns = [
    path("", views.client_list_view, name="client_list"),
    path("add/", views.client_create_view, name="client_create"),
    path("<int:pk>/", views.client_detail_view, name="client_detail"),
    path("<int:pk>/update/", views.client_update_view, name="client_update"),
    path("<int:pk>/delete/", views.client_delete_view, name="client_delete"),
]

core_crm/urls.py
from django.contrib import admin
from django.urls import include, path
from dashboards.views import index, about

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("__reload__/", include("django_browser_reload.urls")),  # django_tailwind
    path("", index, name="homepage"),
    path("about/", about, name="about"),
    path("account/", include("accounts.urls")),
    path("client/", include("clients.urls")),
    path("dashboard/", include("dashboards.urls")),
    path("team/", include("teams.urls")),
    path("lead/", include("leads.urls")),
]

leads/urls.py
from django.urls import path
from . import views

app_name = "leads"
urlpatterns = [
    path("", views.LeadListView.as_view(), name="lead_list"),
    path("add/", views.LeadCreateView.as_view(), name="lead_create"),
    path("<int:pk>/", views.LeadDetailView.as_view(), name="lead_detail"),
    path("<int:pk>/update/", views.LeadUpdateView.as_view(), name="lead_update"),
    path("<int:pk>/delete/", views.LeadDeleteView.as_view(), name="lead_delete"),
    path("<int:pk>/convert/", views.LeadConvertToClientView.as_view(), name="lead_convert"),
]

clients/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from teams.models import Team


class Client(models.Model):
    team = models.ForeignKey(Team, related_name="clients", on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    description = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(
        User, related_name="clients", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("created_at",)

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("clients:client_detail", kwargs={"pk": self.pk})

clients/forms.py
from django import forms

from .models import Client


class ClientCreateForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = (
            "team",
            "first_name",
            "last_name",
            "email",
            "description",
        )
        widgets = {
            "description": forms.Textarea(attrs={"rows": 4, "cols": 15}),
        }

clients/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .forms import ClientCreateForm
from .models import Client

from teams.models import Team


@login_required
def client_list_view(request):
    clients = Client.objects.filter(created_by=request.user)

    context = {
        "clients": clients,
    }
    return render(request, "clients/client_list.html", context)


@login_required
def client_create_view(request):

    team = Team.objects.filter(created_by=request.user)
    client_count = team.clients.count()
    max_clients = team.plan.max_clients

    if request.method == "POST":
        form = ClientCreateForm(request.POST)
        if form.is_valid():
            client = form.save(commit=False)
            client.created_by = request.user
            client.team = team
            client.save()
            messages.success(request, "Client created sucessfully!")
            return redirect("clients:client_list")
    else:
        form = ClientCreateForm()

    context = {
        "team": team,
        "form": form,
        "client_count": client_count,
        "max_clients": max_clients,
    }
    return render(request, "clients/client_create.html", context)


@login_required
def client_detail_view(request, pk):
    client = get_object_or_404(Client, created_by=request.user, id=pk)

    context = {
        "client": client,
    }
    return render(request, "clients/client_detail.html", context)


@login_required
def client_update_view(request, pk):

    client = get_object_or_404(Client, created_by=request.user, id=pk)

    if request.method == "POST":
        form = ClientCreateForm(request.POST, instance=client)
        if form.is_valid():
            form.save()
            messages.success(request, "Client updated sucessfully!")
            return redirect("clients:client_detail", client.pk)
    else:
        form = ClientCreateForm(instance=client)

    context = {
        "client": client,
        "form": form,
    }
    return render(request, "clients/client_update.html", context)


@login_required
def client_delete_view(request, pk):
    client = get_object_or_404(Client, created_by=request.user, id=pk)

    if request.method == "POST":
        client.delete()
        messages.success(request, "Client deleted sucessfully!")
        return redirect("clients:client_list")

    context = {
        "client": client,
    }
    return render(request, "clients/client_delete.html", context)

clients/templates/clients/client_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block title %}Add Client{% endblock title %}


{% block main_content %}
<div class="container px-5 py-16 mx-auto">
    <div class="lg:w-2/5 mx-auto flex flex-wrap">
        {% include 'messages.html' %}
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h1 class="text-4xl text-gray-800">Create a new client</h1>
            {% if client_count < max_clients %}
            <form method="post" class="mt-5">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                    Create
                </button>
            </form>
            {% else %}
            <p class='mt-2 mb-2'>Max Clients: {{ max_clients }}</p>
            <div class="p-4 w-full bg-red-300 border-red-400">
                <p class="text-sm text-red-700">Your team has reached the max client limit.</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock main_content %}

clients/templates/clients/client_delete.html
{% extends 'base.html' %}

{% block title %}Client Delete{% endblock title %}


{% block main_content %}
<div class="max-w-lg mt-20 mx-auto">
    <div class="py-5 border-gray-200">
        <form class="mt-5" action="" method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ client }}"?</p>
            <button class="w-full mt-5 text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md" type="submit">
                Delete
            </button>
        </form>
        <div class="py-5">
            <a class="hover:text-blue-500 underline" href="{% url 'clients:client_detail' client.pk %}">Cancel</a>
        </div>
    </div>
</div>
{% endblock main_content %}

clients/templates/clients/client_detail.html
{% extends 'base.html' %}

{% block title %}Client Detail{% endblock title %}


{% block main_content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-3/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">CLIENT</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ client }}</h1>
                <div class="flex mb-4">
                    <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Overview
                    </a>
                    <a href="{% url 'clients:client_update' client.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Update Details
                    </a>
                </div>
                {% if client.description %}
                    <p class="leading-relaxed mb-4">{{ client.description }}</p>
                {% endif %}
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Age</span>
                    <span class="ml-auto text-gray-900">{{ client.age }}</span>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Created at</span>
                    <span class="ml-auto text-gray-900">{{ client.created_at }}</span>
                </div>
                <div class="flex border-t border-b mb-6 border-gray-300 py-2">
                    <span class="text-gray-500">Updated at</span>
                    <span class="ml-auto text-gray-900">{{ client.updated_at }}</span>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock main_content %}

clients/templates/clients/client_list.html
{% extends 'base.html' %}

{% block title %}Clients{% endblock title %}


{% block main_content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        {% include 'messages.html' %}
        <div class="w-full mb-6 py-6 flex justify-between item-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Clients</h1>
            </div>
            <div>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'clients:client_create' %}">Create a new client</a>
            </div>
        </div>

        <div class="flex flex-col w-full">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                        <table class="min-w-full divide-y divide-gray-200">
                            {% if clients %}
                            <thead class="bg-gray-50">
                                <tr>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        First Name
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Last Name
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Email
                                    </th>
                                    <th scope="col" class="relative px-6 py-3">
                                        <span class="sr-only">Edit</span>
                                    </th>
                                </tr>
                            </thead>
                            {% endif %}
                            <tbody>
                            {% for client in clients %}
                                <tr class="bg-white">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        <a class="hover:text-indigo-500" href="{% url 'clients:client_detail' client.pk %}">{{ client.first_name }}</a>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {{ client.last_name }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {{ client.email }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a href="{% url 'clients:client_update' client.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                            Edit
                                        </a>
                                    </td>
                                </tr>
                            {% empty %}
                            <p>There are currently no clients</p>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>

{% endblock main_content %}

clients/templates/clients/client_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block title %}Edit Client{% endblock title %}


{% block main_content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-3/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead }}</h1>
                <div class="flex mb-4">
                    <a href="{% url 'clients:client_detail' client.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Overview
                    </a>
                    <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Update Details
                    </a>
                </div>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                        Update
                    </button>
                </form>
                <div class="mt-5 py-5 border-t border-gray-200">
                    <a href="{% url 'clients:client_delete' client.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                        Delete
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock main_content %}