accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path("detail/", views.my_account_details_view, name="account_detail"),
    path("login/", views.AccountLoginView.as_view(), name="login"),
    path("logout/", views.AccountLogoutView.as_view(), name="logout"),
]

clients/urls.py
from django.urls import path
from . import views

app_name = "clients"
urlpatterns = [
    path("", views.client_list_view, name="client_list"),
    path("add/", views.client_create_view, name="client_create"),
    path("<int:pk>/", views.client_detail_view, name="client_detail"),
    path("<int:pk>/update/", views.client_update_view, name="client_update"),
    path("<int:pk>/delete/", views.client_delete_view, name="client_delete"),
]

core_crm/urls.py
from django.contrib import admin
from django.urls import include, path
from dashboards.views import index, about

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("__reload__/", include("django_browser_reload.urls")),  # django_tailwind
    path("", index, name="homepage"),
    path("about/", about, name="about"),
    path("account/", include("accounts.urls")),
    path("client/", include("clients.urls")),
    path("dashboard/", include("dashboards.urls")),
    path("team/", include("teams.urls")),
    path("lead/", include("leads.urls")),
]

dashboards/urls.py
from django.urls import path
from . import views


app_name = "dashboards"
urlpatterns = [
    path("", views.dashboard_view, name="dashboard"),
]

leads/urls.py
from django.urls import path
from . import views

app_name = "leads"
urlpatterns = [
    path("", views.LeadListView.as_view(), name="lead_list"),
    path("add/", views.LeadCreateView.as_view(), name="lead_create"),
    path("<int:pk>/", views.LeadDetailView.as_view(), name="lead_detail"),
    path("<int:pk>/update/", views.LeadUpdateView.as_view(), name="lead_update"),
    path("<int:pk>/delete/", views.LeadDeleteView.as_view(), name="lead_delete"),
    path("<int:pk>/convert/", views.LeadConvertToClientView.as_view(), name="lead_convert"),
]

templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock title %}

{% block main_content %}
About Page
{% endblock main_content %}

templates/base.html
{% load static %}
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
</head>
<body class="flex flex-col min-h-screen">  <!-- this class fixes footer at bottom -->
  {% include 'navbar.html' %}
  
  {% block main_content %}{% endblock main_content %}

  {% include 'footer.html' %}
</body>
</html>

templates/footer.html
{% load static %}

<footer class="text-gray-600 body-font mt-auto">
  <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
    <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
      <span class="ml-3 text-xl">CRM</span>
    </a>
    <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">© 2023 CRM —
      <a href="#" class="text-gray-600 ml-1" rel="noopener noreferrer" target="_blank">@arpan</a>
    </p>
    <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
      <a class="text-gray-500">
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
          <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
          <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
          <circle cx="4" cy="4" r="2" stroke="none"></circle>
        </svg>
      </a>
    </span>
  </div>
</footer>

templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block main_content %}
<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
        <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="{% static 'images/dashboard.svg' %}">
        <div class="text-center lg:w-2/3 w-full">
            <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
                CRM built with Django
            </h1>
            <p class="mb-8 leading-relaxed">
                This CRM helps you manage your leads.
            </p>
            {% if not request.user.is_authenticated %}
            <div class="flex justify-center">
                <a href="{% url 'accounts:login' %}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
                    Login to get started
                </a>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock main_content %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="p-4 w-full
        {% if message.tags == 'success' %}
        bg-green-600 border-green-400
        {% elif message.tags == 'info' %}
        bg-blue-50 border-blue-400
        {% elif message.tags == 'warning' %}
        bg-yellow-50 border-yellow-400
        {% else %}
        bg-red-50 border-red-400
        {% endif %}
        ">
            <p class="text-sm
            {% if message.tags == 'success' %}
            text-green-100
            {% elif message.tags == 'info' %}
            text-blue-700
            {% elif message.tags == 'warning' %}
            text-yellow-700
            {% else %}
            text-red-700
            {% endif %}
            ">
                {{ message }}
            </p>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load static %}

<header class="text-gray-600 body-font bg-teal-900">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
        <a href="{% url 'homepage' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
            <img src="{% static 'images/logo.svg' %}" alt="logo">
            <span class="ml-3 text-xl text-stone-50">CRM</span>
        </a>
        <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
            <a href="{% url 'dashboards:dashboard' %}" class="mr-5 text-stone-200 hover:text-stone-50">Dashboard</a>
            <a href="{% url 'clients:client_list' %}" class="mr-5 text-stone-200 hover:text-stone-50">Clients</a>
            <a href="{% url 'leads:lead_list' %}" class="mr-5 text-stone-200 hover:text-stone-50">Leads</a>
            <a href="{% url 'about' %}" class="mr-5 text-stone-200 hover:text-stone-50">About</a>
        </nav>
        {% if request.user.is_authenticated %}
        <a href="{% url 'accounts:logout' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
            Logout
        </a>
        {% else %}
        <a href="{% url 'accounts:signup' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
            Signup
        </a>
        <a href="{% url 'accounts:login' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
            Login
        </a>
        {% endif %}
    </div>
</header>